version: '2'
services:
  order_api_app:
    container_name: order_api_app
    restart: always
    build: .
    ports:
    - 8080:8080
    links:
    - order_mongo_db

  order_mongo_db:
    container_name: order_mongo_db
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"
